### ISSUE TITLE
Load with empty array

### ISSUE THREAD

**Issue by makcumka2000** [ElisDN/yii2-composite-form#1]
I have a parent form:
``
class ProductCreateForm extends CompositeForm
``
And it has a nested forms:
``
$this->paramForms = array_map(function (Parameter $param) {
            return new ParameterTableEntryForm($param);
        }, Parameter::find()->all());
``
My business logic allow to $this->paramForms may be empty array ($this->paramForms = [])
But load form:
``
$form->load(Yii::$app->request->post())
``
Return false, because yii2 Model::loadMultiple return false if array is empty.

Is there any descision?

**Comment by makcumka2000** [comment]
I wanna change CompositeForm::load:
```php
$success = parent::attributes() ? parent::load($data, $formName) : !empty($data);
        foreach ($this->forms as $name => $form) {
            if (is_array($form)) {
                if ($form !== []) {
                    $success = Model::loadMultiple($form, $data, $formName === null ? null : $name) && $success;
                }
            } else {
                $success = $form->load($data, $formName !== '' ? null : $name) && $success;
            }
        }
        return $success;
```
But $forms it is private property and I can not do it

**Comment by ElisDN** [comment]
Fixed. Thanks!
