### ISSUE TITLE
Метод load должен возвращать true, если есть хотя бы одно поле/форма

### ISSUE THREAD

**Issue by vjik** [ElisDN/yii2-composite-form#2]
При определении успешности выполнения метода `load` должно использоваться ИЛИ вместо И.
Вместо `$success = … && $success;` надо `$success = … || $success;`.

Ведь логика стандартного `load` — если есть хотя бы одно поле из этой формы, то вернуть true. А сейчас получается true возвращается только в случае, если есть ВСЕ формы.

**Comment by ElisDN** [comment]
Исправил. Спасибо!
